[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "ziggy-pydust-template"
version = "0.1.0"
description = ""
authors = [{ name = "Fulcrum Inc.", email = "hello@fulcrum.so" }]
requires-python = "~=3.11"
readme = "README.md"

[dependency-groups]
dev = [
    "ziggy-pydust==0.23.2",
    "pytest>=8.0.0,<9",
    "ruff>=0.4.0,<0.5",
    "black>=23.7.0,<24",
]

[tool.hatch.build.targets.sdist]
include = [
    "fibonacci",
    "src/",
    "fibonacci/*.pyi",
]

[tool.hatch.build.targets.wheel]
include = [
    "fibonacci",
    "fibonacci/*.so",
    "fibonacci/*.pyi",
]

[tool.black]
line-length = 120

[tool.ruff]
line-length = 120
select = ["F", "E", "W", "UP", "I001", "I002"]

[[tool.pydust.ext_module]]
name = "fibonacci._lib"
root = "src/fib.zig"
