name: CI

on:
  push:
    branches: ["develop"]
  pull_request:
    branches: ["develop"]

permissions:
  actions: read
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      - name: 📦 Install uv
        uses: astral-sh/setup-uv@v4

      - name: 🐍 Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: 🦾 Install dependencies
        run: uv sync --all-extras --dev

      - name: 🔍 Lint with Ruff
        run: uv run ruff check .

      - name: 🖌️ Format with Black
        run: uv run black --check .

      - name: 🧪 Run tests
        run: uv run pytest

      - name: 🔎 Check stubs
        run: uv run python -m ziglang build generate-stubs -Dcheck-stubs=true